version: "3.8"

services:
  ui:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
  api:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
