version: "3.8"

services:
  # Backend
  Backend:
    build: ./Backend
    expose:
      - ${APP_SERVER_PORT}
    environment:
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SEVER_PORT}
    command: npm start

  # Frontend
  Frontend:
    build: ./Frontend
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    links:
      - Backend
    command: npm start
