const dbConfig = require("../config/db.config.js");
const mongoose = require("mongoose");
const db = {};
db.mongoose = mongoose;
db.url = dbConfig.url;
db.users = require("./user.model.js")(mongoose);
db.threads = require("./thread.model.js")(mongoose);
db.threadPosts = require("./threadPost.model.js")(mongoose);
module.exports = db;
